name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install and build
      run: |
        npm ci
        npm run build
    - name: deploy
      if: success()
      uses: maxheld83/ghpages@v0.2.1
      with:
        build_dir: dist
